;
; File generated by cc65 v 2.19 - Git 6efe447
;
	.fopt		compiler,"cc65 v 2.19 - Git 6efe447"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.export		_main

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	lda     #$FF
	sta     $6002
	lda     #$55
L0005:	sta     $6000
	eor     #$FF
	jmp     L0005

.endproc

